### ISSUE TITLE
'eos_weights' args missing

### ISSUE THREAD

**Issue by liyaxin999** [KaijuML/dtt-multi-branch#1]
when you run
`python3 data/format_weights.py --orig download --dest train_weights.txt --strategy thresholds --thresholds 0.4 --normalize --weight_regularization 1`

the argument --eos_weights seems to be required, what value do you suggest?

Thank you

**Comment by KaijuML** [comment]
Hi, 

Thanks for bringing this issue to our attention. I have updated the REAME.md instructions to include the `--eos_weights` arguments. The script should now run correctly with the updated command.

The `eos_weights` is used to balance the responsability of generating the End-of-Sequence token between branches. We've experimented with several configurations, which had minimal impact on performances. Results reported in the paper used  `--eos_weights 1 0`

Also note that in the process of checking if things worked alright, we've found that the link for the `download` file pointed to a wrong version of the file. This has also been fixed, be sure to re-download the correct file:

```bash
wget https://datacloud.di.unito.it/index.php/s/KPr9HnbMyNWqRdj/download
```

I am closing this issue, but feel free to reopen in the case we've overlooked something.

Cheers,
Clément
