### ISSUE TITLE
Issues when running dependency parsing script

### ISSUE THREAD

**Issue by juelap** [KaijuML/dtt-multi-branch#3]
After successfully running the script for POS-tagging, I am facing issues on the dependency parsing part. When running the respective command `python3 dep_parsing_spacy.py --orig wikibio/train_output.txt --dest wikibio/train_deprel.txt --format sent`, I get the following error:

```bash
Loading sentences...
[OK] (526575 sentences in 14.364 seconds)
Loading SpaCy parser...
[OK] (1.922 seconds)
Using 32 processes, starting now.
Parsing sentences:   0%|                                                                                                          | 0/526575 [00:00<?, ?it/s]
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/opt/conda/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "dep_parsing_spacy.py", line 94, in _deal_with_one_instance
    ret = nlp.parser(Doc(nlp.vocab, sentence))
AttributeError: 'English' object has no attribute 'parser'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "dep_parsing_spacy.py", line 111, in <module>
    total=len(sentences)
  File "dep_parsing_spacy.py", line 104, in <listcomp>
    processed_sentences = [item for item in tqdm.tqdm(
  File "/opt/conda/lib/python3.7/site-packages/tqdm/std.py", line 1178, in __iter__
    for obj in iterable:
  File "/opt/conda/lib/python3.7/multiprocessing/pool.py", line 325, in <genexpr>
    return (item for chunk in result for item in chunk)
  File "/opt/conda/lib/python3.7/multiprocessing/pool.py", line 748, in next
    raise value
AttributeError: 'English' object has no attribute 'parser'
```

I an using the default _spacy_ of version 3.0.6, but maybe some other version is needed.

**Comment by marco-roberti** [comment]
Hello Juela,

During our experiments, we tested various dependency parsers, including SpaCy (version `2.2.4`, for the records 🙂), Stanza, and AllenNLP. As stated in Appendix A of our paper, we finally used Stanza (version `1.2`). I've just committed the right script, `dep_parsing_gpu.py` which you can run as 
```bash
python3 dep_parsing_gpu.py --orig wikibio/train_output.txt --dest wikibio/train_deprel.txt --parser stanza --bsize 64 --format sent
```
Of course, you can adjust `--bsize` depending on your available GPU memory.

Thank you for pointing out this misalignment! Clément and I are always available to assist in solving any issue, so for any other problem do not hesitate.

Best,
Marco

**Comment by juelap** [comment]
Hi Marco,

It seems to be running fine now.
Thanks a lot for the help :)

Best,
Juela
