### ISSUE TITLE
Typo in sentence scoring script

### ISSUE THREAD

**Issue by juelap** [KaijuML/dtt-multi-branch#4]
When running the sentence scoring script, there is a typo in one of the import statements [here](https://github.com/KaijuML/dtt-multi-branch/blob/0ef7759b4d3b3698e6652f88bf1f147e7701070f/data/co_occurrence.py#L15). Since we already are inside `data` folder when running the cmd, then the import should rather be `from utils import FileIterable, TaggedFileIterable` in order to avoid import errors.

**Comment by KaijuML** [comment]
Hi Juela,

Thanks again for noticing! It's fixed now.

Cheers,
Clément

**Comment by juelap** [comment]
If when running the updated `from utils import FileIterable, TaggedFileIterable` command still gives _ModuleNotFoundError_, then add a `.` in front of the module like this: `from .utils import FileIterable, TaggedFileIterable`.

**Comment by KaijuML** [comment]
This is weird because the script runs fine on my end, without `.`. Are you running the command from the `data` directory?

**Comment by juelap** [comment]
Yes, I am. Maybe the reason might be that I am using Python 3.7, and not 3.8.
